version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.0-node

    working_directory: ~/repo/

    steps:
      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: install-dependencies
          command: bundler install

      - run:
          name: execute-test
          command: bundle exec cucumber

  feature-express:
    docker:
      - image: circleci/node:8
      
    working_directory: ~/repo/
    
    steps:
      - checkout
      
      - run:
          name: install-dependencies
          command: cd feature-express && npm install
        
      - run:
          name: build-feature-express
          command: cd feature-express && npm run build-feature-express

  deploy-master:
    requires:
      - test
      - feature-express
    filters:
      branches:
        only: master

workflows:
  version: 2
  test_and_feature-express_and_deploy-master:
    jobs:
      - test
      - feature-express
      - deploy-master