# use CircleCI 2.0
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # - run:
      #     name: install-dependencies
      #     command: npm install

      - run: # run tests
          name: feature-express
          command: make build-feature-express