version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLER_VERSION: 2.0.1

    working_directory: ~/repo/

    steps:
      - checkout

      - run:
          name: install-dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: execute-test
          command: bundle exec cucumber

  # test:
  #   docker:
  #     - image: circleci/node:8
      
  #   working_directory: ~/repo/
    
  #   steps:
  #     - checkout
      
  #     - run:
  #       name: install-dependencies
  #       command: cd feature-express && npm install
        
  #     - run:
  #       name: build-feature-express
  #       command: cd feature-express && npm run build-feature-express


# workflows:
#   version: 2
#     build:
#       jobs:
#         - build
#         # - feature-express