# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: yoant/circleci-node-ruby

    working_directory: ~/repo

    steps:
      - checkout

      # Cucumber
      # - run: make test

      # Feature-express
      - run: build-feature-express