version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node

    working_directory: ~/repo/

    steps:
      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: install-dependencies
          command: bundler install

      - run:
          name: execute-test
          command: bundle exec cucumber

  # test:
  #   docker:
  #     - image: circleci/node:8
      
  #   working_directory: ~/repo/
    
  #   steps:
  #     - checkout
      
  #     - run:
  #       name: install-dependencies
  #       command: cd feature-express && npm install
        
  #     - run:
  #       name: build-feature-express
  #       command: cd feature-express && npm run build-feature-express


workflows:
  version: 2
    build:
      jobs:
        - build
#         # - feature-express